export const catalogs = [
  {
    id: 1,
    imgUrl: "img/catalog/1.png",
    name: "Встраиваемый светильник Markt",
    price: "3 490 p",
    oldPrice: " 5 060 p",
  },
  {
    id: 2,
    imgUrl: "img/catalog/2.png",
    name: "Линейный светильник ARG",
    price: "6 700 p",
    oldPrice: "",
  },
  {
    id: 3,
    imgUrl: "img/catalog/3.png",
    name: "Сведодиодный светильник",
    price: "5 060 p",
    oldPrice: " 6 060 p",
  },
  {
    id: 4,
    imgUrl: "img/catalog/1.png",
    name: "Встраиваемый светильник Markt",
    price: "3 490 p",
    oldPrice: "",
  },
  {
    id: 5,
    imgUrl: "img/catalog/2.png",
    name: "Встраиваемый светильник Markt",
    price: "6 700 p",
    oldPrice: " 7 060 p",
  },
  {
    id: 6,
    imgUrl: "img/catalog/3.png",
    name: "Встраиваемый светильник Markt",
    price: "5 060 p",
    oldPrice: "",
  },
  {
    id: 7,
    imgUrl: "img/catalog/1.png",
    name: "Встраиваемый светильник Markt",
    price: "3 490 p",
    oldPrice: " 4 060 p",
  },
  {
    id: 8,
    imgUrl: "img/catalog/2.png",
    name: "Встраиваемый светильник Markt",
    price: "6 700 p",
    oldPrice: "",
  },
];
